builds:
- env:
  - CGO_ENABLED=0
  goos: [linux]
  goarch: [amd64, arm, arm64, 386]
  goarm: [6, 7]
archive:
  wrap_in_directory: true
  format: tar.gz
  replacements:
    386: i386
    amd64: x86_64
  files:
    - examples/**/*
    - templates/**/*
    - assets/**/*
    - pages/**/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
